set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='luna'

Plugin 'flazz/vim-colorschemes'

Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-rhubarb'

Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'

Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-session'

Plugin 'AndrewRadev/sideways.vim'

Plugin 'StanAngeloff/php.vim'

Plugin 'w0rp/ale'

Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'

Plugin 'editorconfig/editorconfig-vim'

Plugin 'prettier/vim-prettier'

Plugin 'norcalli/nvim-colorizer.lua'

Plugin 'kamykn/spelunker.vim'

Plugin 'stephpy/vim-php-cs-fixer'

call vundle#end()
filetype plugin indent on

colorscheme luna

let mapleader = ','

" Expand tabs into spaces
set expandtab

" Use smart tabs
set smarttab

" Tab length = 4 spaces
set shiftwidth=4
set tabstop=4

" Auto indent
set autoindent

" Filetype overrides
autocmd Filetype json setlocal ts=2 sw=2 sts=2
autocmd Filetype html setlocal ts=2 sw=2 sts=2
autocmd Filetype javascript setlocal ts=2 sw=2 sts=2
autocmd Filetype yaml setlocal ts=2 sw=2 sts=2

" PHP syntax overrides
function! PhpSyntaxOverride()
  hi! def link phpDocTags  phpDefine
  hi! def link phpDocParam phpType
  hi! def link phpStaticClasses phpIdentifier
endfunction
augroup phpSyntaxOverride
  autocmd!
  autocmd FileType php call PhpSyntaxOverride()
augroup END

" Disable slow syntax in php.vim
" See https://github.com/StanAngeloff/php.vim/issues/68
let php_html_load = 0
let php_html_in_heredoc = 0
let php_html_in_nowdoc = 0
let php_sql_query = 0
let php_sql_heredoc = 0
let php_sql_nowdoc = 0

" Use smart case for text searches
set ignorecase
set smartcase

" Show relative line numbers
set number
set relativenumber

set background=dark

" Allow switching from unsaved buffers
set hidden

set wildmode=longest,list

set tags^=.git/tags;~

let g:session_autosave = 'yes'
let g:session_autoload = 'yes'

" Map Ctrl-C to Esc
vnoremap <C-c> <Esc>
nnoremap <C-c> <Esc>
inoremap <C-c> <Esc>

" Disable mouse
set mouse-=a
"
" Buffer navigation
map gn :bn<cr>
map gp :bp<cr>
map gN :bp<cr>

nnoremap <c-h> :SidewaysLeft<cr>
nnoremap <c-l> :SidewaysRight<cr>

nnoremap <c-]> :tjump <C-R><C-W><cr>

nnoremap <leader>f :GFiles --recurse-submodules<cr>

" Use system clipboard for unnamed register
set clipboard+=unnamedplus

" Wayland clipboard provider that strips carriage returns (GTK3 issue).
" This is needed because currently there's an issue where GTK3 applications on
" Wayland contain carriage returns at the end of the lines (this is a root
" issue that needs to be fixed).
" See: https://github.com/neovim/neovim/issues/10223#issuecomment-521952122
" See: https://gitlab.gnome.org/GNOME/gtk/issues/2307
let g:clipboard = {
      \   'name': 'wayland-strip-carriage',
      \   'copy': {
      \      '+': 'wl-copy --foreground --type text/plain',
      \      '*': 'wl-copy --foreground --type text/plain --primary',
      \    },
      \   'paste': {
      \      '+': {-> systemlist('wl-paste | tr -d "\r"')},
      \      '*': {-> systemlist('wl-paste --primary | tr -d "\r"')},
      \   },
      \   'cache_enabled': 1,
      \ }



let g:ale_sign_column_always = 1

" Turned spelunker off for the moment because of performance issues with large
" files
let g:enable_spelunker_vim = 0
let g:spelunker_check_type = 1

let g:php_cs_fixer_path = "./bin/php-cs-fixer"

autocmd ColorScheme * highlight SpelunkerSpellBad cterm=underline ctermfg=160 gui=underline guifg=#de4e4e
autocmd ColorScheme * highlight SpelunkerComplexOrCompoundWord cterm=underline ctermfg=160 gui=underline guifg=#de4e4e

" Show whitespace characters
set list
set listchars=tab:→\ ,space:·
autocmd ColorScheme * highlight NonText ctermfg=235 guifg=#353535

" Highlight extra whitespace
autocmd ColorScheme * highlight ExtraWhitespace guifg=#870000 guibg=#ffa40b
highlight ExtraWhitespace ctermbg=red guibg=red

" Highlight trailing whitespace, spaces before a tab, and tabs not at the
" start of a line
match ExtraWhitespace /\s\+$\| \+\ze\t\|[^\t"#\/]\zs\t\+/
" Disable trailing whitespace match in insert mode.
au InsertEnter * match ExtraWhitespace / \+\ze\t\|[^\t"#\/]\zs\t\+/
" Reenable when leaving insert
au InsertLeave * match ExtraWhitespace /\s\+$\| \+\ze\t\|[^\t"#\/]\zs\t\+/

" Disable Ex mode
map q: <Nop>
nnoremap Q <nop>

" Disable mapping of Ctrl-C to SQL completion...
let g:omni_sql_no_default_maps = 1

" Prettier autoformat
let g:prettier#autoformat = 0
autocmd BufWritePre *.php silent! call PhpCsFixerFixFile()
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.md,*.vue,*.yaml,*.html,*.php PrettierAsync

" disable folding
set nofoldenable

autocmd Colorscheme * hi NonText guibg=NONE ctermbg=NONE
                  \ | hi Normal guibg=NONE ctermbg=NONE
