set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline_theme='luna'

Plugin 'flazz/vim-colorschemes'

Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-rhubarb'

Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'

Plugin 'xolox/vim-misc'
Plugin 'xolox/vim-session'

Plugin 'AndrewRadev/sideways.vim'

Plugin 'StanAngeloff/php.vim'

Plugin 'w0rp/ale'

Plugin 'pangloss/vim-javascript'
Plugin 'mxw/vim-jsx'

call vundle#end()
filetype plugin indent on

colorscheme luna

let mapleader = ','

" Expand tabs into spaces
set expandtab

" Use smart tabs
set smarttab

" Tab length = 4 spaces
set shiftwidth=4
set tabstop=4

" Auto indent
set autoindent

" Filetype overrides
autocmd Filetype json setlocal ts=2 sw=2 sts=2
autocmd Filetype html setlocal ts=2 sw=2 sts=2
autocmd Filetype javascript setlocal ts=2 sw=2 sts=2
autocmd Filetype yaml setlocal ts=2 sw=2 sts=2

" PHP syntax overrides
function! PhpSyntaxOverride()
  hi! def link phpDocTags  phpDefine
  hi! def link phpDocParam phpType
  hi! def link phpStaticClasses phpIdentifier
endfunction
augroup phpSyntaxOverride
  autocmd!
  autocmd FileType php call PhpSyntaxOverride()
augroup END

" Use smart case for text searches
set ignorecase
set smartcase

" Show relative line numbers
set number
set relativenumber

set background=dark

set hidden

set wildmode=longest,list

let g:session_autosave = 'yes'
let g:session_autoload = 'yes'

" Map Ctrl-C to Esc
vnoremap <C-c> <Esc>
nnoremap <C-c> <Esc>
inoremap <C-c> <Esc>

" Disable mouse
set mouse-=a
"
" Buffer navigation
map gn :bn<cr>
map gp :bp<cr>
map gN :bp<cr>

nnoremap <c-h> :SidewaysLeft<cr>
nnoremap <c-l> :SidewaysRight<cr>

nnoremap <c-]> :tjump <C-R><C-W><cr>

nnoremap <leader>f :GFiles --recurse-submodules<cr>

" Use system clipboard for unnamed register
set clipboard+=unnamedplus

let g:ale_sign_column_always = 1
